### ISSUE TITLE
Spitballing :)

### ISSUE THREAD

**Issue by tghc** [sensepost/rattler#5]
Great tool!

not necessarily a feature request but just spitballing ... what do you think about these ideas -

Looking for .exe's and .js files too - previously when looking for ways to feed files into applications that have returned NAME_NOT_FOUND I've seen .exe's and .js 

- it might be cool! 

also maybe nice to allow a rattler user to submit the found issues to a contribution list? - might be cool! 

I hope you dont mind me chiming in

**Comment by brompwnie** [comment]
Hi there!
Thanks for the feedback, always great to hear ideas from users of the tool. I'm gonna to add this as feature enhancement.
